import "./App.css";
import Landing from "./landing/Landing";

import Amplify from 'aws-amplify';
import awsconfig from './aws-exports'; // This file is generated by Amplify

Amplify.configure(awsconfig);


function App() {
  return (
    <div>
      <Landing />
    </div>
  );
}

export default App; 
